version: 2
jobs:
  build:
    docker:
    - image: circleci/android:api-27

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-

    - run: mkdir secrets
    - run: echo $KEY_STORE | base64 --decode > secrets/testAppKS
    - run: echo $SERVICE_ACCOUNT_JSON | base64 --decode > secrets/serviceAccount.json
    - run: ./gradlew androidDependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run: ./gradlew test

    - run:
      name: Setup emulator
      command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"

    - run:
        name: Launch emulator
        command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
        background: true

    - run:
        name: Run Tests
        command: ./gradlew :demo:connectedAndroidTest
#    - run: ./gradlew publish