version: 2
jobs:
  build:
    docker:
    - image: circleci/android:api-27

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-

    - run: mkdir secrets && echo $KEY_STORE | base64 --decode > secrets/testAppKS
    - run: ./gradlew androidDependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run: ./gradlew test
    - run: ./gradlew publish