version: 2
jobs:
  build:
    docker:
    - image: circleci/android@sha256:5cdc8626cc6f13efe5ed982cdcdb432b0472f8740fed8743a6461e025ad6cdfc

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - v1-dependencies-

    - run: mkdir secrets
    - run: echo $KEY_STORE | base64 --decode > secrets/testAppKS
    - run: echo $SERVICE_ACCOUNT_JSON | base64 --decode > secrets/serviceAccount.json
    - run: ./gradlew androidDependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

    - run: ./gradlew test
    - run: ./gradlew publish
