version: 2
jobs:
  build:
    docker:
    - image: circleci/android@sha256:5cdc8626cc6f13efe5ed982cdcdb432b0472f8740fed8743a6461e025ad6cdfc

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - v1-dependencies-

    - run: mkdir secrets
    - run: echo $KEY_STORE | base64 --decode > secrets/testAppKS
    - run: echo $SERVICE_ACCOUNT_JSON | base64 --decode > secrets/serviceAccount.json
    - run: ./gradlew androidDependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

    - run: ./gradlew test

    - run: |
        set -e
        sudo apt-get update
        sudo apt-get install --fix-missing mesa-utils
        # Source https://github.com/bitrise-docker/android/blob/7ab19405c13da614f54c17dffb79bcbb490b5fb9/Dockerfile#L149
        sudo apt-get install -y --fix-missing libqt5widgets5

    - run: |
        # echo "Listing of /opt/android/sdk"
        sdkmanager — list — verbose | grep system-images
        # I tried API 25 but it is too slow and times out on Circle CI
        sdkmanager "system-images;android-28;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-28;default;armeabi-v7a"

    - run:
        name: Launch emulator
        command: emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
        background: true

    - run: circle-android wait-for-boot

    - run: ./gradlew connectedAndroidTest